FROM nginx as base

RUN apt-get -y update && apt-get -y install vim

FROM base
COPY  ./.docker/nginx.conf /etc/nginx/nginx.conf
COPY  ./.docker/app.conf /etc/nginx/conf.d/sites-available/app.conf
RUN mkdir -p /etc/nginx/conf.d/sites-enabled
WORKDIR /etc/nginx/conf.d/sites-enabled
RUN ln -s ../sites-available/app.conf .

EXPOSE 80/tcp
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]