version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cfg:/etc/nginx/conf.d/
      - ./certs:/etc/ssl/private

  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - 3000:3000